from pathlib import Path
p=Path('frontend/src/components/TaskConfigForm.vue')
t=p.read_text(encoding='utf-8')
mark='        <el-form-item label="批量追加"><el-input v-model="forms.groupEngagement.bulkRulesText"'
if mark not in t: raise SystemExit('mark missing')
extra="          <div class=\"extra-parts\">\n            <div v-for=\"(part, pIndex) in (rule.extraTexts || [])\" :key=\"part.id\" class=\"extra-part\">\n              <el-form-item :label=\"'附加文字 ' + (pIndex + 1)\">\n                <el-input v-model=\"part.text\" type=\"textarea\" :rows=\"3\" />\n                <el-button link type=\"danger\" @click=\"rule.extraTexts.splice(pIndex, 1)\">删除</el-button>\n              </el-form-item>\n            </div>\n            <div v-for=\"(part, pIndex) in (rule.extraImages || [])\" :key=\"part.id\" class=\"extra-part\">\n              <el-form-item :label=\"'附加图片 ' + (pIndex + 1)\">\n                <el-select v-model=\"part.imageDictionaryName\" class=\"full\" placeholder=\"选择图片字典\">\n                  <el-option label=\"不发送\" value=\"\" />\n                  <el-option v-for=\"name in imageDictionaryNames\" :key=\"name\" :label=\"name\" :value=\"name\" />\n                </el-select>\n                <el-select v-model=\"part.materialDictionaryName\" class=\"full\" placeholder=\"或选素材底图\" style=\"margin-top:8px\">\n                  <el-option label=\"不使用素材\" value=\"\" />\n                  <el-option v-for=\"name in materialDictionaryNames\" :key=\"'m'+name\" :label=\"name\" :value=\"name\" />\n                </el-select>\n                <el-button link type=\"danger\" @click=\"rule.extraImages.splice(pIndex, 1)\">删除</el-button>\n              </el-form-item>\n            </div>\n            <div class=\"form-hint no-offset compact\">\n              <el-button size=\"small\" @click=\"addExtraText(rule)\">添加文字</el-button>\n              <el-button size=\"small\" @click=\"addExtraImage(rule)\">添加图片</el-button>\n              每条规则可追加多段文字和多张图片，发送时按顺序发出。\n            </div>\n          </div>\n"
t=t.replace(mark, extra+mark, 1)
p.write_text(t, encoding='utf-8')
print('extra ui ok')
