from pathlib import Path
lines=[]
A=lines.append
A("using Microsoft.EntityFrameworkCore.Infrastructure;")
A("using Microsoft.EntityFrameworkCore.Migrations;")
A("")
A("#nullable disable")
A("")
A("namespace TelegramPanel.Data.Migrations;")
A("")
A("[DbContext(typeof(AppDbContext))]")
A("[Migration(\"20260917120000_AddBatchTaskLogs\")]")
A("public partial class AddBatchTaskLogs : Migration")
A("{")
A("    protected override void Up(MigrationBuilder migrationBuilder)")
A("    {")
A("        migrationBuilder.CreateTable(")
A("            name: \"BatchTaskLogs\",")
A("            columns: table => new")
A("            {")
A("                Id = table.Column<long>(nullable: false).Annotation(\"Sqlite:Autoincrement\", true),")
A("                BatchTaskId = table.Column<int>(nullable: false),")
A("                Level = table.Column<string>(maxLength: 20, nullable: false),")
A("                Message = table.Column<string>(maxLength: 4000, nullable: false),")
A("                CreatedAt = table.Column<DateTime>(nullable: false)")
A("            },")
A("            constraints: table =>")
A("            {")
A("                table.PrimaryKey(\"PK_BatchTaskLogs\", x => x.Id);")
A("            });")
A("        migrationBuilder.CreateIndex(\"IX_BatchTaskLogs_BatchTaskId_CreatedAt\", \"BatchTaskLogs\", new[] { \"BatchTaskId\", \"CreatedAt\" });")
A("    }")
A("")
A("    protected override void Down(MigrationBuilder migrationBuilder)")
A("    {")
A("        migrationBuilder.DropTable(\"BatchTaskLogs\");")
A("    }")
A("}")
Path('src/TelegramPanel.Data/Migrations/20260917120000_AddBatchTaskLogs.cs').write_text('\n'.join(lines)+'\n', encoding='utf-8')
print('ok')
