from pathlib import Path
lines = []
A = lines.append
A("using SixLabors.ImageSharp;")
A("using SixLabors.ImageSharp.PixelFormats;")
A("using SixLabors.ImageSharp.Processing;")
A("")
A("namespace TelegramPanel.Web.Services;")
A("")
A("public sealed class MaterialMockupRequest")
A("{")
A("    public string DeviceId { get; set; } = \"iphone-16-pro-max\";")
A("    public string TimeMode { get; set; } = \"now\";")
A("    public string? Time { get; set; }")
A("    public double Scale { get; set; } = 1;")
A("    public string Notification { get; set; } = \"none\";")
A("}")
A("")
A("public sealed class MaterialMockupService")
A("{")
A("    private sealed record DeviceSpec(int Width, int Height, string Platform, float StatusFraction);")
A("    private static readonly Dictionary<string, DeviceSpec> Devices = new(StringComparer.OrdinalIgnoreCase)")
A("    {")
A("        [\"iphone-16-pro-max\"] = new(440, 956, \"ios\", 0.054f),")
A("        [\"iphone-16-pro\"] = new(402, 874, \"ios\", 0.054f),")
A("        [\"iphone-16-plus\"] = new(430, 932, \"ios\", 0.054f),")
A("        [\"iphone-16\"] = new(393, 852, \"ios\", 0.054f),")
A("        [\"iphone-15-pro-max\"] = new(430, 932, \"ios\", 0.054f),")
A("        [\"iphone-14-pro-max\"] = new(430, 932, \"ios\", 0.054f),")
A("        [\"pixel-7-pro\"] = new(412, 816, \"android\", 48f / 816f),")
A("        [\"pixel-8-pro\"] = new(448, 921, \"android\", 48f / 921f),")
A("        [\"galaxy-s24\"] = new(360, 780, \"android\", 48f / 780f),")
A("        [\"galaxy-a55\"] = new(480, 1040, \"android\", 48f / 1040f),")
A("    };")
A("")
A("    public async Task<byte[]> ComposeAsync(Stream baseImage, MaterialMockupRequest request, CancellationToken cancellationToken = default)")
A("    {")
A("        if (!Devices.TryGetValue((request.DeviceId ?? string.Empty).Trim(), out var device))")
A("            device = Devices[\"iphone-16-pro-max\"];")
A("        var scale = request.Scale <= 0 ? 1 : Math.Clamp(request.Scale, 0.5, 2);")
A("        var screenW = Math.Max(220, (int)Math.Round(device.Width * scale));")
A("        var screenH = Math.Max(400, (int)Math.Round(device.Height * scale));")
A("        var statusH = Math.Max(28, (int)Math.Round(screenH * device.StatusFraction));")
A("        var homeH = Math.Max(12, (int)Math.Round(screenH * 0.025));")
A("        var contentH = Math.Max(80, screenH - statusH - homeH);")
A("        var clock = ResolveTime(request);")
A("        using var source = await Image.LoadAsync<Rgba32>(baseImage, cancellationToken);")
A("        source.Mutate(x => x.Resize(new ResizeOptions { Size = new Size(screenW, contentH), Mode = ResizeMode.Crop, Position = AnchorPositionMode.Top }));")
A("        using var canvas = new Image<Rgba32>(screenW, screenH, Color.White);")
A("        DrawStatusBar(canvas, screenW, statusH, clock, device.Platform, request.Notification);")
A("        canvas.Mutate(x => x.DrawImage(source, new Point(0, statusH), 1f));")
A("        DrawHomeIndicator(canvas, screenW, statusH + contentH, homeH);")
A("        await using var ms = new MemoryStream();")
A("        await canvas.SaveAsPngAsync(ms, cancellationToken);")
A("        return ms.ToArray();")
A("    }")
A("")
A("    private static string ResolveTime(MaterialMockupRequest request)")
A("    {")
A("        if (string.Equals(request.TimeMode, \"fixed\", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrWhiteSpace(request.Time))")
A("            return request.Time.Trim();")
A("        TimeZoneInfo tz;")
A("        try { tz = TimeZoneInfo.FindSystemTimeZoneById(\"Asia/Shanghai\"); }")
A("        catch { tz = TimeZoneInfo.FindSystemTimeZoneById(\"China Standard Time\"); }")
A("        return TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, tz).ToString(\"HH:mm\");")
A("    }")
A("")
A("    private static void DrawStatusBar(Image<Rgba32> canvas, int width, int height, string clock, string platform, string notification)")
A("    {")
A("        FillRect(canvas, 0, 0, width, height, new Rgba32(255, 255, 255));")
A("        var unit = Math.Max(1, height / 14);")
A("        DrawText(canvas, 12, Math.Max(6, height / 2 - unit * 4), clock, new Rgba32(17, 17, 17), unit);")
A("        if (platform == \"ios\")")
A("        {")
A("            var pillW = Math.Max(48, width / 5);")
A("            var pillH = Math.Max(12, height / 2);")
A("            FillRect(canvas, (width - pillW) / 2, Math.Max(4, height / 6), pillW, pillH, new Rgba32(5, 5, 5));")
A("        }")
A("        else if (string.Equals(notification, \"telegram\", StringComparison.OrdinalIgnoreCase))")
A("        {")
A("            DrawTelegramMark(canvas, 12 + clock.Length * unit * 6, Math.Max(6, height / 3), unit * 2);")
A("        }")
A("        DrawSignal(canvas, width - height * 3, height / 3, unit);")
A("    }")
A("")
A("    private static void DrawHomeIndicator(Image<Rgba32> canvas, int width, int top, int height)")
A("    {")
A("        FillRect(canvas, 0, top, width, height, new Rgba32(255, 255, 255));")
A("        var barW = Math.Max(40, width / 4);")
A("        var barH = Math.Max(3, height / 5);")
A("        FillRect(canvas, (width - barW) / 2, top + height / 2, barW, barH, new Rgba32(0, 0, 0));")
A("    }")
A("")
A("    private static void DrawSignal(Image<Rgba32> canvas, int x, int y, int unit)")
A("    {")
A("        for (var i = 0; i < 4; i++)")
A("        {")
A("            var h = (i + 1) * unit;")
A("            FillRect(canvas, x + i * (unit + 1), y + 4 * unit - h, unit, h, new Rgba32(17, 17, 17));")
A("        }")
A("        FillRect(canvas, x + 6 * unit, y + unit, unit * 3, unit * 2, new Rgba32(17, 17, 17));")
A("    }")
A("")
A("    private static void DrawTelegramMark(Image<Rgba32> canvas, int x, int y, int size)")
A("    {")
A("        for (var i = 0; i < size; i++)")
A("            FillRect(canvas, x + i, y + size / 2 - i / 3, Math.Max(1, size - i), Math.Max(1, i / 2 + 1), new Rgba32(17, 17, 17));")
A("    }")
A("")
A("    private static readonly Dictionary<char, string[]> Glyphs = new()")
A("    {")
A("        ['0'] = new[] { \"111\", \"101\", \"101\", \"101\", \"111\" },")
A("        ['1'] = new[] { \"010\", \"110\", \"010\", \"010\", \"111\" },")
A("        ['2'] = new[] { \"111\", \"001\", \"111\", \"100\", \"111\" },")
A("        ['3'] = new[] { \"111\", \"001\", \"111\", \"001\", \"111\" },")
A("        ['4'] = new[] { \"101\", \"101\", \"111\", \"001\", \"001\" },")
A("        ['5'] = new[] { \"111\", \"100\", \"111\", \"001\", \"111\" },")
A("        ['6'] = new[] { \"111\", \"100\", \"111\", \"101\", \"111\" },")
A("        ['7'] = new[] { \"111\", \"001\", \"001\", \"001\", \"001\" },")
A("        ['8'] = new[] { \"111\", \"101\", \"111\", \"101\", \"111\" },")
A("        ['9'] = new[] { \"111\", \"101\", \"111\", \"001\", \"111\" },")
A("        [':'] = new[] { \"0\", \"1\", \"0\", \"1\", \"0\" },")
A("    };")
A("")
A("    private static void DrawText(Image<Rgba32> canvas, int x, int y, string text, Rgba32 color, int unit)")
A("    {")
A("        var cx = x;")
A("        foreach (var ch in text)")
A("        {")
A("            if (!Glyphs.TryGetValue(ch, out var rows)) { cx += unit * 3; continue; }")
A("            for (var r = 0; r < rows.Length; r++)")
A("            for (var c = 0; c < rows[r].Length; c++)")
A("                if (rows[r][c] == '1')")
A("                    FillRect(canvas, cx + c * unit, y + r * unit, unit, unit, color);")
A("            cx += (rows[0].Length + 1) * unit;")
A("        }")
A("    }")
A("")
A("    private static void FillRect(Image<Rgba32> canvas, int x, int y, int w, int h, Rgba32 color)")
A("    {")
A("        var x2 = Math.Min(canvas.Width, x + w);")
A("        var y2 = Math.Min(canvas.Height, y + h);")
A("        x = Math.Max(0, x); y = Math.Max(0, y);")
A("        for (var yy = y; yy < y2; yy++)")
A("        for (var xx = x; xx < x2; xx++)")
A("            canvas[xx, yy] = color;")
A("    }")
A("}")
Path('src/TelegramPanel.Web/Services/MaterialMockupService.cs').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('wrote', Path('src/TelegramPanel.Web/Services/MaterialMockupService.cs').stat().st_size)
