<template>
  <div class="lookup-page">
    <el-alert v-if="loadError" :title="loadError" type="error" show-icon :closable="false" class="mb"><el-button size="small" @click="loadOptions">重新加载选项</el-button></el-alert>
    <el-card shadow="never" class="page-card">
      <el-form label-position="top">
        <el-form-item label="查询目标"><el-input v-model="form.targets" type="textarea" :rows="7" placeholder="单个或每行一个：+1 123 456 7890、1234567890、@username；手机号可包含空格，不接受其他符号。"/></el-form-item>
        <div class="grid"><el-form-item label="账号来源"><el-radio-group v-model="form.source"><el-radio-button value="account">指定账号</el-radio-button><el-radio-button value="category">账号分类轮询</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="form.source==='account'" label="执行账号"><el-select v-model="form.accountId" filterable class="full"><el-option v-for="a in usableAccounts" :key="a.id" :label="accountLabel(a)" :value="a.id"/></el-select></el-form-item><el-form-item v-else label="账号分类"><el-select v-model="form.categoryId" class="full"><el-option v-for="c in categories" :key="c.id" :label="`${c.name}（${c.accountCount}）`" :value="c.id"/></el-select></el-form-item></div>
        <div class="grid three"><el-form-item label="最小间隔（秒）"><el-input-number v-model="form.minDelay" :min="0" :max="3600"/></el-form-item><el-form-item label="最大间隔（秒）"><el-input-number v-model="form.maxDelay" :min="form.minDelay" :max="3600"/></el-form-item><el-form-item label="目标模式"><el-radio-group v-model="form.order"><el-radio-button value="queue">队列</el-radio-button><el-radio-button value="random">随机</el-radio-button></el-radio-group></el-form-item></div>
        <el-alert title="单个目标立即返回。批量实时查询会占用当前页面，请设置合理间隔；大量目标请发送任务。" type="warning" :closable="false" class="mb"/>
        <el-button type="primary" :loading="running" @click="start(false)">实时查询</el-button><el-button :loading="running" @click="start(true)">发送任务</el-button><el-button v-if="running" type="danger" plain @click="cancelled=true">停止</el-button>
      </el-form>
    </el-card>
    <el-card shadow="never" class="page-card mt-4"><template #header><div class="header"><b>当前查询结果</b><span>共 {{results.length}} 条，{{done}} / {{targets.length}}</span></div></template>
      <el-table :data="results" stripe empty-text="暂无查询结果"><el-table-column prop="query" label="查询目标" min-width="145"/><el-table-column label="结果" width="105"><template #default="{row}"><el-tag :type="row.result.found?'success':row.error?'danger':'warning'">{{row.result.found?'存在':row.error?'异常':'未找到'}}</el-tag></template></el-table-column><el-table-column label="客户列表" width="105"><template #default="{row}">{{row.existingCustomer?'已更新':'未收录'}}</template></el-table-column><el-table-column label="用户ID" min-width="125"><template #default="{row}">{{row.result.userId||'-'}}</template></el-table-column><el-table-column label="姓名" min-width="120"><template #default="{row}">{{row.result.displayName||'-'}}</template></el-table-column><el-table-column label="用户名" min-width="130"><template #default="{row}">{{row.result.username?'@'+row.result.username:'-'}}</template></el-table-column><el-table-column label="手机号" min-width="140"><template #default="{row}">{{row.result.phone||'-'}}</template></el-table-column><el-table-column label="头像" width="70"><template #default="{row}">{{yn(row.result.hasPhoto)}}</template></el-table-column><el-table-column label="活跃状态" min-width="145"><template #default="{row}">{{activity(row.result)}}</template></el-table-column><el-table-column label="Premium" width="90"><template #default="{row}">{{yn(row.result.isPremium)}}</template></el-table-column><el-table-column label="机器人" width="72"><template #default="{row}">{{yn(row.result.isBot)}}</template></el-table-column><el-table-column label="认证" width="70"><template #default="{row}">{{yn(row.result.isVerified)}}</template></el-table-column><el-table-column label="诈骗号" width="75"><template #default="{row}">{{yn(row.result.isScam)}}</template></el-table-column><el-table-column label="虚假号" width="75"><template #default="{row}">{{yn(row.result.isFake)}}</template></el-table-column><el-table-column label="注销号" width="75"><template #default="{row}">{{yn(row.result.isDeleted)}}</template></el-table-column><el-table-column label="生日" width="105"><template #default="{row}">{{row.result.birthday||'-'}}</template></el-table-column><el-table-column prop="error" label="说明" min-width="180"/></el-table>
    </el-card>
  </div>
</template>
<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'; import {ElMessage,ElMessageBox} from 'element-plus'; import {panelApi} from '@/api/panel'; import type {AccountCategory,AccountListItem,CustomerLookupEnvelope,UserLookupResult} from '@/api/types'; import {formatTime} from '@/utils/format'
type Row=CustomerLookupEnvelope&{query:string;error?:string}; const accounts=ref<AccountListItem[]>([]),categories=ref<AccountCategory[]>([]),results=ref<Row[]>([]),running=ref(false),cancelled=ref(false),done=ref(0),loadError=ref(''); const form=reactive({targets:'',source:'account',accountId:undefined as number|undefined,categoryId:undefined as number|undefined,minDelay:3,maxDelay:8,order:'queue'})
const usableAccounts=computed(()=>accounts.value.filter(a=>a.isActive&&a.telegramStatusOk!==false)),targets=computed(()=>form.targets.split(/[\r\n,;]+/).map(x=>x.trim()).filter(Boolean)); const selectedAccounts=computed(()=>form.source==='account'?usableAccounts.value.filter(x=>x.id===form.accountId):usableAccounts.value.filter(x=>x.category?.id===form.categoryId)); const accountLabel=(a:AccountListItem)=>`${a.displayPhone}(${a.nickname||a.remark||'-'})${a.username?'@'+a.username:''}`; const yn=(v:boolean)=>v?'有':'无'; const activity=(r:UserLookupResult)=>({online:'当前在线',offline:r.lastSeenAt?`最后上线 ${formatTime(r.lastSeenAt)}`:'最后上线时间',recently:'最近上线',last_week:'一周内上线',last_month:'一个月内上线',unknown:'状态未知/不可见'}[r.activityStatus]||'状态未知/不可见'); const empty=(q:string,e:string):UserLookupResult=>({found:false,query:q,hasPhoto:false,activityStatus:'unknown',isPremium:false,isBot:false,isVerified:false,isScam:false,isFake:false,isDeleted:false,isRestricted:false,error:e})
async function loadOptions(){const rs=await Promise.allSettled([panelApi.accounts({page:1,pageSize:500,categoryId:null,search:'',onlyWaste:false}),panelApi.accountCategories()]);if(rs[0].status==='fulfilled'){accounts.value=rs[0].value.items;form.accountId??=usableAccounts.value[0]?.id}if(rs[1].status==='fulfilled')categories.value=rs[1].value;loadError.value=rs.some(x=>x.status==='rejected')?'部分账号选项加载失败，已保留可用数据。':''}
function normalize(v:string){if(v.startsWith('@'))return /^@[A-Za-z0-9_]{3,32}$/.test(v)?v:null;if(!/^\+?[0-9 ]+$/.test(v))return null;const d=v.replace(/\D/g,'');return d.length>=7&&d.length<=15?'+'+d:null} const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function start(asTask:boolean){const bad=targets.value.find(x=>!normalize(x));if(bad)return ElMessage.error(`格式错误：${bad}`);if(!targets.value.length)return ElMessage.warning('请输入查询目标');if(!selectedAccounts.value.length)return ElMessage.warning('请选择至少一个可用执行账号');if(targets.value.length>1&&!asTask)await ElMessageBox.confirm('批量实时查询将占用当前页面。请确认已设置合理间隔；大量查询请发送任务。','批量实时查询',{type:'warning'});if(asTask)ElMessage.info('任务已开始，可在本页查看实时进度，请勿关闭页面。');running.value=true;cancelled.value=false;done.value=0;results.value=[];let list=targets.value.map(x=>normalize(x)!).filter(Boolean);if(form.order==='random')list=list.sort(()=>Math.random()-.5);for(let i=0;i<list.length&&!cancelled.value;i++){const q=list[i],a=selectedAccounts.value[i%selectedAccounts.value.length];try{const out=await panelApi.lookupNewCustomer(q,a.id);results.value.push({...out,query:q,error:out.result.error||undefined})}catch(e:any){const msg=e?.response?.data?.message||e?.message||'查询失败';results.value.push({query:q,existingCustomer:false,result:empty(q,msg),error:msg})}done.value++;if(i<list.length-1){const sec=form.minDelay+Math.random()*Math.max(0,form.maxDelay-form.minDelay);await sleep(sec*1000)}}running.value=false;ElMessage.success(cancelled.value?'查询已停止':'查询完成')}
onMounted(loadOptions)
</script>
<style scoped>.lookup-page{min-width:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grid.three{grid-template-columns:repeat(3,1fr)}.full{width:100%}.mb{margin-bottom:16px}.header{display:flex;justify-content:space-between}.mt-4{margin-top:16px}@media(max-width:760px){.grid,.grid.three{grid-template-columns:1fr}}</style>
