<template><div class="lookup-page">
  <el-alert v-if="loadError" :title="loadError" type="error" show-icon :closable="false" class="mb"/>
  <el-card shadow="never" class="page-card"><el-form label-position="top">
    <el-form-item label="查询目标"><el-input v-model="form.targets" type="textarea" :rows="6" placeholder="单个或每行一个：+1 123 456 7890、1234567890、@username"/></el-form-item>
    <div class="grid"><el-form-item label="账号来源"><el-radio-group v-model="form.source"><el-radio-button value="account">指定账号（多选）</el-radio-button><el-radio-button value="category">账号分类轮询</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="form.source==='category'" label="账号分类"><el-select v-model="form.categoryId" class="full"><el-option v-for="c in categories" :key="c.id" :label="`${c.name}（${c.accountCount}）`" :value="c.id"/></el-select></el-form-item></div>
    <div v-if="form.source==='account'" class="account-picker"><div class="picker-actions"><el-button size="small" @click="selectAllAccounts">全选本页</el-button><el-button size="small" @click="clearAccounts">取消全选</el-button><span class="muted">已选 {{selectedAccountIds.length}} 个执行账号</span></div>
      <el-table ref="accountTable" :data="usableAccounts" row-key="id" size="small" class="fixed-table" @selection-change="onAccountSelection"><el-table-column type="selection" width="48" reserve-selection/><el-table-column prop="displayPhone" label="手机号" min-width="150"/><el-table-column label="昵称" min-width="130"><template #default="{row}">{{row.nickname||row.remark||'-'}}</template></el-table-column><el-table-column label="用户名" min-width="130"><template #default="{row}">{{row.username?'@'+row.username:'-'}}</template></el-table-column><el-table-column label="Telegram 状态" min-width="150"><template #default="{row}">{{row.telegramStatusSummary||'未检测'}}</template></el-table-column><el-table-column label="最后数据同步" min-width="170"><template #default="{row}">{{formatTime(row.lastSyncAt)}}</template></el-table-column><el-table-column label="操作" fixed="right" width="100"><template #default="{row}"><el-button link type="danger" @click="removeSelectedAccount(row)">移出选择</el-button></template></el-table-column></el-table>
    </div>
    <div class="grid three"><el-form-item label="最小间隔（秒）"><el-input-number v-model="form.minDelay" :min="0" :max="3600"/></el-form-item><el-form-item label="最大间隔（秒）"><el-input-number v-model="form.maxDelay" :min="form.minDelay" :max="3600"/></el-form-item><el-form-item label="目标模式"><el-radio-group v-model="form.order"><el-radio-button value="queue">队列</el-radio-button><el-radio-button value="random">随机</el-radio-button></el-radio-group></el-form-item></div>
    <el-alert title="查询先持久化批次；关闭页面、切换路由或容器重启后仍可在任务中心跟踪。" type="success" :closable="false" class="mb"/><el-button type="primary" :loading="submitting" @click="start('realtime')">实时查询</el-button><el-button :loading="submitting" @click="start('task')">发送任务</el-button>
  </el-form></el-card>
  <el-card shadow="never" class="page-card mt-4"><template #header><div class="header"><b>当前查询结果</b><span v-if="currentBatch">{{currentBatch.completed}} / {{currentBatch.total}}，找到 {{currentBatch.found}}，失败 {{currentBatch.failed}}</span></div></template>
    <el-table :data="results" stripe empty-text="请选择历史批次或创建查询"><el-table-column prop="rawTarget" label="查询目标" min-width="145"/><el-table-column label="结果" width="105"><template #default="{row}"><el-tag :type="row.status==='found'?'success':row.status==='failed'?'danger':'warning'">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column label="客户列表" width="105"><template #default="{row}">{{row.existingCustomer?'已更新':'未收录'}}</template></el-table-column><el-table-column prop="telegramUserId" label="用户ID" min-width="125"/><el-table-column prop="displayName" label="姓名" min-width="120"/><el-table-column label="用户名" min-width="130"><template #default="{row}">{{row.username?'@'+row.username:'-'}}</template></el-table-column><el-table-column prop="phone" label="手机号" min-width="140"/><el-table-column label="头像" width="70"><template #default="{row}">{{yn(row.hasPhoto)}}</template></el-table-column><el-table-column label="活跃状态" min-width="145"><template #default="{row}">{{activity(row)}}</template></el-table-column><el-table-column label="Premium" width="90"><template #default="{row}">{{yn(row.isPremium)}}</template></el-table-column><el-table-column prop="error" label="说明" min-width="180"/></el-table>
  </el-card>
  <el-card shadow="never" class="page-card mt-4"><template #header><div class="header"><b>历史查询批次</b><el-button size="small" @click="loadHistory">刷新</el-button></div></template><el-table :data="history" row-key="id" class="fixed-table"><el-table-column prop="name" label="名称" min-width="180"/><el-table-column prop="status" label="状态" width="100"/><el-table-column label="进度" width="130"><template #default="{row}">{{row.completed}} / {{row.total}}</template></el-table-column><el-table-column label="创建时间" min-width="170"><template #default="{row}">{{formatTime(row.createdAt)}}</template></el-table-column><el-table-column label="操作" width="210" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openBatch(row.id)">查看</el-button><el-button link type="warning" :disabled="active(row)" @click="retryBatch(row.id)">失败重试</el-button><el-button link type="danger" :disabled="active(row)" @click="deleteBatch(row.id)">删除记录</el-button></template></el-table-column></el-table></el-card>
</div></template>
<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,reactive,ref} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {panelApi} from '@/api/panel';import type {AccountCategory,AccountListItem,CustomerLookupBatch,CustomerLookupItem} from '@/api/types';import {formatTime} from '@/utils/format'
const accounts=ref<AccountListItem[]>([]),categories=ref<AccountCategory[]>([]),selectedAccountIds=ref<number[]>([]),accountTable=ref(),history=ref<CustomerLookupBatch[]>([]),results=ref<CustomerLookupItem[]>([]),currentBatch=ref<CustomerLookupBatch|null>(null),submitting=ref(false),loadError=ref('');const form=reactive({targets:'',source:'account',categoryId:undefined as number|undefined,minDelay:3,maxDelay:8,order:'queue'});let timer:number|undefined
const usableAccounts=computed(()=>accounts.value.filter(a=>a.isActive&&a.telegramStatusOk!==false)),targets=computed(()=>form.targets.split(/[\r\n,;]+/).map(x=>x.trim()).filter(Boolean)),yn=(v:boolean)=>v?'有':'无',active=(b:CustomerLookupBatch)=>['pending','running'].includes(b.status),statusLabel=(v:string)=>({pending:'等待',running:'查询中',found:'存在',not_found:'未找到',failed:'异常'}[v]||v),activity=(r:CustomerLookupItem)=>({online:'当前在线',offline:r.lastSeenAt?`最后上线 ${formatTime(r.lastSeenAt)}`:'最后上线时间',recently:'最近上线',last_week:'一周内上线',last_month:'一个月内上线',unknown:'状态未知/不可见'}[r.activityStatus]||'状态未知/不可见')
async function loadOptions(){const rs=await Promise.allSettled([panelApi.accounts({page:1,pageSize:500,categoryId:null,search:'',onlyWaste:false}),panelApi.accountCategories()]);if(rs[0].status==='fulfilled')accounts.value=rs[0].value.items;if(rs[1].status==='fulfilled')categories.value=rs[1].value;loadError.value=rs.some(x=>x.status==='rejected')?'部分账号选项加载失败。':''}function onAccountSelection(rows:AccountListItem[]){selectedAccountIds.value=rows.map(x=>x.id)}function selectAllAccounts(){usableAccounts.value.forEach(x=>accountTable.value?.toggleRowSelection(x,true))}function clearAccounts(){accountTable.value?.clearSelection()}function removeSelectedAccount(row:AccountListItem){accountTable.value?.toggleRowSelection(row,false)}
async function start(mode:string){if(!targets.value.length)return ElMessage.warning('请输入查询目标');if(form.source==='account'&&!selectedAccountIds.value.length)return ElMessage.warning('请选择至少一个执行账号');if(form.source==='category'&&!form.categoryId)return ElMessage.warning('请选择账号分类');submitting.value=true;try{const r=await panelApi.createCustomerLookupBatch({mode,targets:targets.value,accountIds:form.source==='account'?selectedAccountIds.value:[],accountCategoryId:form.source==='category'?form.categoryId:null,targetOrder:form.order,minDelaySeconds:form.minDelay,maxDelaySeconds:form.maxDelay});ElMessage.success(`任务 #${r.taskId} 已进入任务中心`);await loadHistory();await openBatch(r.batchId)}finally{submitting.value=false}}
async function loadHistory(){history.value=(await panelApi.customerLookupBatches({page:1,pageSize:50})).items}async function openBatch(id:number){const r=await panelApi.customerLookupBatch(id);currentBatch.value=r.batch;results.value=r.items;if(timer)clearInterval(timer);if(active(r.batch))timer=window.setInterval(()=>refreshCurrent(id),2000)}async function refreshCurrent(id:number){const r=await panelApi.customerLookupBatch(id);currentBatch.value=r.batch;results.value=r.items;if(!active(r.batch)){if(timer)clearInterval(timer);timer=undefined;await loadHistory()}}async function retryBatch(id:number){const r=await panelApi.retryCustomerLookupBatch(id);ElMessage.success(`重试任务 #${r.taskId} 已创建`);await openBatch(id)}async function deleteBatch(id:number){await ElMessageBox.confirm('删除该查询批次及全部明细？','确认删除',{type:'warning'});await panelApi.deleteCustomerLookupBatch(id);if(currentBatch.value?.id===id){currentBatch.value=null;results.value=[]}await loadHistory()}
onMounted(()=>Promise.all([loadOptions(),loadHistory()]));onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>
<style scoped>.lookup-page{min-width:0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.full{width:100%}.mb{margin-bottom:14px}.header,.picker-actions{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.account-picker{margin-bottom:16px}.picker-actions{justify-content:flex-start;margin-bottom:8px}.muted{color:var(--tp-muted)}.fixed-table :deep(.el-table-fixed-column--right),.fixed-table :deep(.el-table__fixed-right-patch){background:var(--tp-panel)!important;z-index:5!important}.fixed-table :deep(.el-table__body tr:hover>.el-table-fixed-column--right){background:var(--tp-table-row-hover-bg)!important}@media(max-width:760px){.grid,.grid.three{grid-template-columns:1fr}}</style>
