<template>
  <div class="customers-page">
    <div class="page-heading"><div class="breadcrumb">客户管理 / 客户列表</div><h1>客户列表</h1></div>
    <el-card shadow="never" class="toolbar-card"><div class="filter-row">
      <el-select v-model="filters.groupId" clearable placeholder="全部分类" class="filter"><el-option v-for="g in groups" :key="g.id" :label="g.name" :value="g.id" /></el-select>
      <el-select v-model="filters.status" clearable placeholder="查询状态" class="filter"><el-option label="待查询" value="pending"/><el-option label="已找到" value="found"/><el-option label="未确认" value="not_found"/><el-option label="查询异常" value="error"/></el-select>
      <el-select v-model="filters.batchId" clearable placeholder="导入批次" class="filter wide"><el-option v-for="b in batches" :key="b.id" :label="b.name" :value="b.id" /></el-select>
      <el-input v-model="filters.search" clearable placeholder="搜索手机号、用户名、昵称、Telegram ID" class="search" @keyup.enter="search" />
      <el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button>
    </div></el-card>
    <div class="action-bar"><el-button type="primary" @click="importDialog.visible=true">批量导入</el-button><el-button @click="openDirectLookup">查找用户</el-button><el-button :disabled="!selectedIds.length" @click="openBatchGroup">批量修改分类（已选）</el-button><el-button type="danger" plain :disabled="!selectedIds.length" @click="batchDelete">批量删除（已选）</el-button><span class="muted">已选 {{ selectedIds.length }} 项，共 {{ total }} 个客户</span></div>
    <el-card shadow="never"><el-table v-loading="loading" :data="rows" row-key="id" stripe @selection-change="onSelection">
      <el-table-column type="selection" width="48" reserve-selection/><el-table-column prop="id" label="编号" width="82"><template #default="{row}">#{{ row.id }}</template></el-table-column><el-table-column prop="phone" label="手机号" min-width="150"><template #default="{row}">{{ row.phone||'-' }}</template></el-table-column>
      <el-table-column label="客户信息" min-width="210"><template #default="{row}"><div>{{ row.displayName||'-' }}</div><div class="cell-sub">{{ row.username?`@${row.username}`:'无用户名' }}</div></template></el-table-column><el-table-column prop="telegramUserId" label="Telegram ID" min-width="140"><template #default="{row}">{{ row.telegramUserId||'-' }}</template></el-table-column>
      <el-table-column label="查询状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.lookupStatus)">{{ statusLabel(row.lookupStatus) }}</el-tag></template></el-table-column><el-table-column label="客户分类" min-width="160"><template #default="{row}"><el-tag v-for="g in row.groups" :key="g.id" effect="plain" class="tag">{{ g.name }}</el-tag><span v-if="!row.groups.length">未分类</span></template></el-table-column><el-table-column label="最后查询" min-width="170"><template #default="{row}">{{ row.lastLookupAt?formatTime(row.lastLookupAt):'-' }}</template></el-table-column>
      <el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row.id)">查看详情</el-button><el-button link type="primary" :loading="lookupLoadingId===row.id" @click="openRowLookup(row)">查询</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column>
    </el-table><div class="pager"><span>共 {{ total }} 条</span><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.pageSize" layout="sizes, prev, pager, next" :total="total" :page-sizes="[20,50,100]" @change="load"/></div></el-card>

    <el-dialog v-model="importDialog.visible" title="批量导入客户" width="min(680px, calc(100vw - 24px))"><el-alert title="每行一个国际格式手机号或 @用户名；重复项会关联本次批次和所选分类。" type="info" :closable="false"/><el-form label-position="top" class="dialog-form"><el-form-item label="批次名称"><el-input v-model="importDialog.batchName" placeholder="留空自动生成"/></el-form-item><el-form-item label="客户分类"><el-select v-model="importDialog.groupId" clearable class="full"><el-option v-for="g in groups" :key="g.id" :label="g.name" :value="g.id"/></el-select></el-form-item><el-form-item label="手机号 / @用户名"><el-input v-model="importDialog.values" type="textarea" :rows="12" placeholder="+12125550123&#10;@username"/></el-form-item></el-form><template #footer><el-button @click="importDialog.visible=false">取消</el-button><el-button type="primary" :loading="importDialog.saving" @click="submitImport">导入</el-button></template></el-dialog>
    <el-dialog v-model="lookupDialog.visible" title="查找用户" width="min(560px, calc(100vw - 24px))"><el-alert title="选择状态正常的账号执行 Telegram 查询；结果会写入客户档案。手机号结果可能受隐私设置影响。" type="info" :closable="false"/><el-form label-position="top" class="dialog-form"><el-form-item label="手机号或 @用户名"><el-input v-model="lookupDialog.query" :disabled="lookupDialog.customerId>0" placeholder="+12125550123 或 @username"/></el-form-item><el-form-item label="执行账号"><el-select v-model="lookupDialog.accountId" filterable class="full" placeholder="选择执行账号"><el-option v-for="a in usableAccounts" :key="a.id" :label="accountLabel(a)" :value="a.id"/></el-select></el-form-item></el-form><el-alert v-if="lookupDialog.result" :type="lookupDialog.result.found?'success':'warning'" :title="lookupDialog.result.found?'查询成功':(lookupDialog.result.error||'未找到')" :closable="false"><div v-if="lookupDialog.result.found">{{ lookupDialog.result.displayName||'-' }} · {{ lookupDialog.result.username?'@'+lookupDialog.result.username:'无用户名' }} · ID {{ lookupDialog.result.userId }}</div></el-alert><template #footer><el-button @click="lookupDialog.visible=false">关闭</el-button><el-button type="primary" :loading="lookupDialog.loading" :disabled="!lookupDialog.accountId||!lookupDialog.query.trim()" @click="runLookup">立即查询</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog.visible" title="客户详情" width="min(680px, calc(100vw - 24px))"><el-skeleton v-if="detailDialog.loading" :rows="6" animated/><el-descriptions v-else-if="detailDialog.data" :column="2" border><el-descriptions-item label="手机号">{{ detailDialog.data.phone||'-' }}</el-descriptions-item><el-descriptions-item label="用户名">{{ detailDialog.data.username?'@'+detailDialog.data.username:'-' }}</el-descriptions-item><el-descriptions-item label="昵称">{{ detailDialog.data.displayName||'-' }}</el-descriptions-item><el-descriptions-item label="Telegram ID">{{ detailDialog.data.telegramUserId||'-' }}</el-descriptions-item><el-descriptions-item label="查询状态">{{ statusLabel(detailDialog.data.lookupStatus) }}</el-descriptions-item><el-descriptions-item label="最后查询">{{ detailDialog.data.lastLookupAt?formatTime(detailDialog.data.lastLookupAt):'-' }}</el-descriptions-item><el-descriptions-item label="客户分类"><el-tag v-for="g in detailDialog.data.groups" :key="g.id" class="tag">{{ g.name }}</el-tag><span v-if="!detailDialog.data.groups.length">未分类</span></el-descriptions-item><el-descriptions-item label="导入批次"><span v-for="b in detailDialog.data.batches" :key="b.id" class="batch">{{ b.name }}</span><span v-if="!detailDialog.data.batches.length">-</span></el-descriptions-item><el-descriptions-item label="备注" :span="2">{{ detailDialog.data.remark||'-' }}</el-descriptions-item></el-descriptions></el-dialog>
    <el-dialog v-model="batchGroup.visible" title="批量修改客户分类" width="440px"><el-select v-model="batchGroup.groupId" clearable class="full" placeholder="清空选择表示设为未分类"><el-option v-for="g in groups" :key="g.id" :label="g.name" :value="g.id"/></el-select><template #footer><el-button @click="batchGroup.visible=false">取消</el-button><el-button type="primary" :loading="batchGroup.saving" @click="applyBatchGroup">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'; import { ElMessage,ElMessageBox } from 'element-plus'; import { panelApi } from '@/api/panel'; import type { AccountListItem,CustomerDetail,CustomerGroupOption,CustomerImportBatch,CustomerItem,UserLookupResult } from '@/api/types'; import { formatTime } from '@/utils/format'
const loading=ref(false),rows=ref<CustomerItem[]>([]),total=ref(0),groups=ref<CustomerGroupOption[]>([]),batches=ref<CustomerImportBatch[]>([]),accounts=ref<AccountListItem[]>([]),selectedIds=ref<number[]>([]),lookupLoadingId=ref(0)
const filters=reactive({page:1,pageSize:20,search:'',status:'',groupId:undefined as number|undefined,batchId:undefined as number|undefined}),importDialog=reactive({visible:false,saving:false,batchName:'',groupId:undefined as number|undefined,values:''}),lookupDialog=reactive({visible:false,loading:false,customerId:0,query:'',accountId:undefined as number|undefined,result:null as UserLookupResult|null}),detailDialog=reactive({visible:false,loading:false,data:null as CustomerDetail|null}),batchGroup=reactive({visible:false,saving:false,groupId:undefined as number|undefined})
const usableAccounts=computed(()=>accounts.value.filter(a=>a.isActive&&a.telegramStatusOk!==false)),statusLabel=(v:string)=>({pending:'待查询',found:'已找到',not_found:'未确认',error:'查询异常'}[v]||v),statusType=(v:string)=>(v==='found'?'success':v==='pending'?'info':'warning'),accountLabel=(a:AccountListItem)=>`${a.displayPhone}(${a.nickname||a.remark||'-'})${a.username?'@'+a.username:''}`
async function load(){loading.value=true;try{const [r,g,b]=await Promise.all([panelApi.customers({...filters}),panelApi.customerGroups(),panelApi.customerImportBatches()]);rows.value=r.items;total.value=r.total;groups.value=g;batches.value=b}finally{loading.value=false}} async function loadAccounts(){accounts.value=(await panelApi.accounts({page:1,pageSize:500,categoryId:null,search:'',onlyWaste:false})).items} function onSelection(s:CustomerItem[]){selectedIds.value=s.map(x=>x.id)} function search(){filters.page=1;load()} function reset(){Object.assign(filters,{page:1,search:'',status:'',groupId:undefined,batchId:undefined});load()}
async function submitImport(){if(!importDialog.values.trim()){ElMessage.warning('请填写客户');return}importDialog.saving=true;try{const r=await panelApi.importCustomers({values:importDialog.values,batchName:importDialog.batchName||undefined,groupId:importDialog.groupId});ElMessage.success(`导入 ${r.imported}，重复 ${r.duplicates}，无效 ${r.invalid}`);importDialog.visible=false;importDialog.values='';await load()}finally{importDialog.saving=false}} function openDirectLookup(){Object.assign(lookupDialog,{visible:true,customerId:0,query:'',accountId:usableAccounts.value[0]?.id,result:null})} function openRowLookup(row:CustomerItem){Object.assign(lookupDialog,{visible:true,customerId:row.id,query:row.phone||(row.username?'@'+row.username:''),accountId:usableAccounts.value[0]?.id,result:null})}
async function runLookup(){lookupDialog.loading=true;lookupLoadingId.value=lookupDialog.customerId;try{lookupDialog.result=lookupDialog.customerId?await panelApi.lookupCustomer(lookupDialog.customerId,lookupDialog.accountId!):await panelApi.lookupNewCustomer(lookupDialog.query,lookupDialog.accountId!);await load()}finally{lookupDialog.loading=false;lookupLoadingId.value=0}} async function showDetail(id:number){detailDialog.visible=true;detailDialog.loading=true;try{detailDialog.data=await panelApi.customer(id)}finally{detailDialog.loading=false}} async function remove(row:CustomerItem){await ElMessageBox.confirm(`删除客户 #${row.id}？`,'确认删除',{type:'warning'});await panelApi.deleteCustomer(row.id);await load()}
function openBatchGroup(){batchGroup.groupId=undefined;batchGroup.visible=true} async function applyBatchGroup(){batchGroup.saving=true;try{await panelApi.batchCustomers(selectedIds.value,'set_group',batchGroup.groupId??null);batchGroup.visible=false;ElMessage.success('客户分类已更新');await load()}finally{batchGroup.saving=false}} async function batchDelete(){await ElMessageBox.confirm(`删除已选 ${selectedIds.value.length} 个客户？`,'批量删除',{type:'warning'});await panelApi.batchCustomers(selectedIds.value,'delete');selectedIds.value=[];ElMessage.success('删除完成');await load()} onMounted(()=>Promise.all([load(),loadAccounts()]))
</script>
<style scoped>.customers-page{min-width:0}.page-heading{margin-bottom:18px}.page-heading h1{margin:4px 0}.breadcrumb,.muted,.cell-sub{color:var(--tp-muted)}.toolbar-card{margin-bottom:14px}.filter-row,.action-bar{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.filter{width:150px}.wide{width:210px}.search{flex:1;min-width:260px}.action-bar{margin:14px 0}.pager{display:flex;justify-content:flex-end;align-items:center;gap:18px;margin-top:16px}.full{width:100%}.dialog-form{margin-top:16px}.tag{margin-right:5px}.batch{display:block}.el-table :deep(.el-table-fixed-column--right){background:var(--el-bg-color)}@media(max-width:760px){.filter,.wide,.search{width:100%;min-width:100%}}</style>
